### PR TITLE
add limit function to buyer from shop

### PR DESCRIPTION
**Pull request by dhannyjsb**

### CODE REVIEW

**Comment by anes66** [comment]
this will not work with that  method

**Comment by ItsTaras** [comment]
This is not work :S

**Comment by ReneRoets** [comment]
You have to define the 'sourceItem' that why it isn't working.

` local sourceItem = xPlayer.getInventoryItem(Item)`

**Comment by mahmoudourti** [comment]
hello This is not work wen i put 
local sourceItem = xPlayer.getInventoryItem(Item)
he give me 
SCRIPT ERROR: @esx-kr-advanced-shops/server/main.lua:154: attempt to compare nil with number
> ref (@esx-kr-advanced-shops/server/main.lua:154)
>  (@mysql-async/mysql-async.js:14431

**Comment by mahmoudourti** [comment]
hello i have this problem 
SCRIPT ERROR: @esx-kr-advanced-shops/server/main.lua:158: attempt to compare nil with number
>  (@mysql-async/mysql-async.js:14431)

**Review by KRILLE123 — APPROVED** [review]

**Review by KRILLE123 — APPROVED** [review]

**Pull request merged**
